
server {
  listen 7860 default_server;
  listen [::]:7860 default_server;

  server_name _;
  
  
  location /api/ws/ {
        # 代理到后端的 upstream
        proxy_pass http://localhost:5700;
 
        # 关键配置：启用对 WebSocket 的支持
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
 
        # 其他推荐的代理头
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
 
        # 设置代理超时时间，对于长连接很重要
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s; # 可以根据应用需要设置更长的时间，例如 3600s
    }
  
  location / {
		
	  if ($http_x_secret_code != "my-secret-password") {
			root /web;
		}

		if ($http_x_secret_code = "my-secret-password") {
			proxy_pass http://localhost:5700;
		  }
	}
	
	

   proxy_set_header Authorization $http_my_auth;

      # 常用的一些反向代理头，确保后端能正确获取客户端信息
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
}
